# SENDING WHAT APP MSGES TO PARTICULAR ONE AT A CERTAIN TIME
# TIME MUST BE BEFORE 1 MINUTES  BEFORE EXECUTION SINCE IT TAKES TIME TO OPEN WEBWHATSAPP





import pywhatkit
pywhatkit.sendwhatmsg("+918106865608","Hi bro",17,49)